version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  
jobs:
  build:
    docker:
      - image: cimg/openjdk:16.0.0

    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      # build and push Docker image
      - run: mvn clean package
      - run: sudo rm -f ~/.docker/config.json
      - run: |
          docker build -t $DOCKERHUB_USER/studentapi-client .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
          docker push $DOCKERHUB_USER/studentapi-client
          sudo rm -f ~/.docker/config.json

workflows:
  build-test-deploy:
    jobs:
      - heroku/deploy-via-git:
          context:
            - Heroku
