version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.0

    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      # build, run unit test cases and sonar quality
      - run: mvn clean package
      - run: mvn verify sonar:sonar
      - run: sudo rm -f ~/.docker/config.json
      - run: |
          docker build -t $DOCKERHUB_USER/studentapi .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
          docker push $DOCKERHUB_USER/studentapi
          sudo rm -f ~/.docker/config.json


workflows:
  build-test-deploy:
    jobs:
      - build:
          context:
            - Heroku
            - SonarCloud
      - heroku/deploy-via-git:
          requires:
            - build
